
export const skills = [
    { name: 'react', url: 'https://reactjs.org/' },
    { name: 'redux', url: 'https://redux.js.org/docs/introduction/' },
    { name: 'angular 1.x, 4.x & 5', url: 'https://angular.io/' },
    { name: '@ngrx 2-4', url: 'https://github.com/ngrx/platform' },
    { name: 'ES6', url: 'https://babeljs.io/learn-es2015/' },
    { name: 'TypeScript', url: 'https://www.typescriptlang.org/' },
    { name: 'Postgres Sql', url: 'https://www.postgresql.org/' },
    { name: 'Mongo DB', url: 'https://www.mongodb.com/' },
    { name: 'SASS', url: 'http://sass-lang.com/' },
    { name: 'HTML5', url: 'https://www.w3schools.com/html/html5_intro.asp' },
    { name: 'Responsive Web Design', url: 'https://www.w3schools.com/html/html_responsive.asp' },
    { name: 'Node.js 8+', url: 'https://nodejs.org/en/' },
    { name: 'TDD - Jest & Karma/Jasmine', url: 'https://github.com/dwyl/learn-tdd' },
    { name: 'Webpack 1.x-3.x', url: 'https://webpack.js.org/' },
    { name: 'Babel 6-7', url: 'https://babeljs.io/' },
    { name: 'Java 6-8', url: 'http://www.oracle.com/technetwork/java/javase/downloads/index.html' },
    { name: 'C# 4-6', url: 'https://docs.microsoft.com/en-us/dotnet/csharp/' },
    { name: 'Spring MVC', url: 'https://spring.io/guides/gs/serving-web-content/' },
    { name: 'ASP.net MVC 4,5', url: 'https://docs.microsoft.com/en-us/aspnet/mvc/mvc5' },
    { name: 'ASP.net webforms', url: 'https://www.asp.net/web-forms' },
    { name: 'Jquery Mobile', url: 'https://jquerymobile.com/' },
    { name: 'MSSQL', url: 'https://www.microsoft.com/en-ca/sql-server/sql-server-2016x' },
]