
 export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';

 export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES';

 export const NEXT_SLIDE = 'NEXT_SLIDE';

 export const PREV_SLIDE = 'PREV_SLIDE';

 export const SHOW_HIDE_PAPER = 'SHOW_HIDE_PAPER';
